/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontdesksystem;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User PC
 */
public class UserServices extends javax.swing.JFrame {

    /**
     * Creates new form UserServices
     */
    public UserServices() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelSpa = new javax.swing.JLabel();
        jLabelProducts = new javax.swing.JLabel();
        jLabelContact = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelAbout1 = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabelSpa1 = new javax.swing.JLabel();
        jLabelSpa2 = new javax.swing.JLabel();
        jLabelSpa3 = new javax.swing.JLabel();
        jLabelSpa4 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabelSpa5 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabelSpa6 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabelSpa7 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabelSpa8 = new javax.swing.JLabel();
        NiggaBG3 = new javax.swing.JLabel();
        NiggaBG2 = new javax.swing.JLabel();
        NiggaBG1 = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();
        background3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1380, 2329));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSpa.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabelSpa.setText(" SERVICES");
        jLabelSpa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSpa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSpaMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelSpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 94, 50));

        jLabelProducts.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabelProducts.setText("PRODUCTS");
        jLabelProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProductsMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 0, 80, 50));

        jLabelContact.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabelContact.setText("CONTACT");
        jLabelContact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelContactMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 0, 110, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\User PC\\Downloads\\Screenshot_2024-11-17_123822-removebg-preview (2).png")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 127, 50));

        jLabelAbout1.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabelAbout1.setText("ABOUT");
        jLabelAbout1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAbout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAbout1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabelAbout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 0, 70, 50));

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1314, 0, 20, 20));

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 2, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot_2024-11-17_123703-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        jLabel26.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Get Social");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1930, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_facebook (1).png"))); // NOI18N
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1970, -1, 30));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_instagram (1).png"))); // NOI18N
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2000, -1, 30));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_tiktok (1).png"))); // NOI18N
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2030, -1, 30));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_youtube.png"))); // NOI18N
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2060, -1, 30));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_twitter-sign (1).png"))); // NOI18N
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2090, -1, 30));

        jLabel21.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("VAN Salon and Spa");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1970, -1, 30));

        jLabel33.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("vansalonandspa");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 2000, -1, 30));

        jLabel34.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("VSAS");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 2030, -1, 30));

        jLabel35.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("VANSalonAndSpa ");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 2060, -1, 30));

        jLabel36.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("VSAS");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 2090, -1, 30));

        jLabel22.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("© 2024 VAN Salon and Spa | All Rights Reserved | Privacy Policy | Terms & Conditions");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 2140, -1, -1));

        jLabel25.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Appointments@VANSalonAndSpa.com");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 2030, -1, 30));

        jLabel23.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("0912 345 6789");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 2000, -1, 40));

        jLabel45.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Brgy. Bucana, Nasugbu Batangas");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 1980, -1, 20));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_pin.png"))); // NOI18N
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 1970, -1, 30));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_call (1).png"))); // NOI18N
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 2000, -1, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_email2 (1).png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 2030, 30, 30));

        jLabel39.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText(" Contacts");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 1930, -1, -1));

        jLabel38.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Hours");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 1930, -1, -1));

        jLabel40.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Mon : 7:00 am - 8:00 pm");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 1960, -1, 40));

        jLabel41.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Tue : 7:00 am - 8:00 pm");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 1980, -1, 40));

        jLabel42.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Wed : 7:00 am - 8:00 pm");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 2010, -1, 20));

        jLabel43.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Thurs : 7:00 am - 8:00 pm");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 2030, -1, 20));

        jLabel44.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Fri : 7:00 am - 8:00 pm");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 2050, 160, 20));

        jLabel46.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Sat: 7:00 am - 8:00 pm");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 2070, 150, 20));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/462537887_580053814602662_2758245647023974022_n.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 1980, -1, -1));

        jLabel14.setFont(new java.awt.Font("Perpetua Titling MT", 1, 60)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Our services");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, 80));

        jLabel50.setFont(new java.awt.Font("Perpetua", 1, 48)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("salon services");
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, -1, 80));

        jLabel51.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Nail Extension");
        jPanel1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 850, -1, 30));

        jLabel54.setFont(new java.awt.Font("Perpetua", 2, 24)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Php 1,500.00");
        jPanel1.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 800, -1, 50));

        jLabel55.setFont(new java.awt.Font("Perpetua", 2, 24)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Php 2,000.00");
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 850, -1, 30));

        jLabel56.setFont(new java.awt.Font("Perpetua", 2, 24)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Php 900.00");
        jPanel1.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 930, -1, 30));

        jLabel57.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("-- nails --");
        jPanel1.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 750, -1, 50));

        jLabel58.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("Pedicure");
        jPanel1.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 930, 100, 30));

        jLabel59.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Gel Manicure");
        jPanel1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 800, -1, 50));

        jLabel60.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("-- hair cut --");
        jPanel1.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, -1, 50));

        jLabel61.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("Women's Cut");
        jPanel1.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, -1, 50));

        jLabel62.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("Men's Cut");
        jPanel1.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 600, -1, 30));

        jLabel63.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("Kid's Cut");
        jPanel1.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 640, 90, 30));

        jLabel64.setFont(new java.awt.Font("Perpetua", 2, 24)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("Php 600.00");
        jPanel1.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 550, -1, 50));

        jLabel65.setFont(new java.awt.Font("Perpetua", 2, 24)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("Php 500.00");
        jPanel1.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 600, -1, 30));

        jLabel66.setFont(new java.awt.Font("Perpetua", 2, 24)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("Php 400.00");
        jPanel1.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 640, -1, 30));

        jLabel74.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("-- hair color --");
        jPanel1.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 770, -1, 50));

        jLabel75.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("Single Process Color");
        jPanel1.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 810, -1, 50));

        jLabel76.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(255, 255, 255));
        jLabel76.setText("Highlights");
        jPanel1.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 860, -1, 30));

        jLabel77.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(255, 255, 255));
        jLabel77.setText("Ombre");
        jPanel1.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 940, 100, 30));

        jLabel78.setFont(new java.awt.Font("Perpetua", 2, 24)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(255, 255, 255));
        jLabel78.setText("Php 1,000.00");
        jPanel1.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 810, -1, 50));

        jLabel79.setFont(new java.awt.Font("Perpetua", 2, 24)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(255, 255, 255));
        jLabel79.setText("Php 1,200.00");
        jPanel1.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 860, -1, 30));

        jLabel80.setFont(new java.awt.Font("Perpetua", 2, 24)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setText("Php 1,400.00");
        jPanel1.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 940, -1, 30));

        jLabel67.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("-- make-up --");
        jPanel1.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 490, -1, 50));

        jLabel68.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Bridal Make-Up");
        jPanel1.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 540, -1, 50));

        jLabel69.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("Party Make-Up");
        jPanel1.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 590, -1, 30));

        jLabel70.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("Day Make-Up");
        jPanel1.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 630, 140, 30));

        jLabel71.setFont(new java.awt.Font("Perpetua", 2, 24)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Php 2,000.00");
        jPanel1.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 540, -1, 50));

        jLabel72.setFont(new java.awt.Font("Perpetua", 2, 24)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("Php 1,500.00");
        jPanel1.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 590, -1, 30));

        jLabel73.setFont(new java.awt.Font("Perpetua", 2, 24)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("Php 1,200.00");
        jPanel1.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 630, -1, 30));

        jLabel81.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(255, 255, 255));
        jLabel81.setText("Balayage");
        jPanel1.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 900, 100, 30));

        jLabel82.setFont(new java.awt.Font("Perpetua", 2, 24)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(255, 255, 255));
        jLabel82.setText("Php 1,500.00");
        jPanel1.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 900, -1, 30));

        jLabel83.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(255, 255, 255));
        jLabel83.setText("Manicure");
        jPanel1.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 890, 100, 30));

        jLabel84.setFont(new java.awt.Font("Perpetua", 2, 24)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(255, 255, 255));
        jLabel84.setText("Php 1,000.00");
        jPanel1.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 890, -1, 30));

        jLabelSpa1.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabelSpa1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSpa1.setText(" SERVICES");
        jLabelSpa1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSpa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSpa1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelSpa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 650, 80, 50));

        jLabelSpa2.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabelSpa2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSpa2.setText(" SERVICES");
        jLabelSpa2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSpa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSpa2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelSpa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 960, 80, 50));

        jLabelSpa3.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabelSpa3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSpa3.setText(" SERVICES");
        jLabelSpa3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSpa3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSpa3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelSpa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 950, 80, 50));

        jLabelSpa4.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabelSpa4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSpa4.setText(" SERVICES");
        jLabelSpa4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSpa4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSpa4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelSpa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 660, 80, 50));

        jLabel52.setFont(new java.awt.Font("Perpetua", 1, 48)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("spa services");
        jPanel1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 1110, -1, 80));

        jLabel85.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(255, 255, 255));
        jLabel85.setText("-- massage --");
        jPanel1.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 1200, -1, 50));

        jLabel86.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(255, 255, 255));
        jLabel86.setText("Sport's Massage");
        jPanel1.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1250, -1, 50));

        jLabel87.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel87.setForeground(new java.awt.Color(255, 255, 255));
        jLabel87.setText("Swedish Massage");
        jPanel1.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1300, -1, 30));

        jLabel88.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(255, 255, 255));
        jLabel88.setText("Thai Massage");
        jPanel1.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1340, 150, 30));

        jLabel89.setFont(new java.awt.Font("Perpetua", 2, 24)); // NOI18N
        jLabel89.setForeground(new java.awt.Color(255, 255, 255));
        jLabel89.setText("Php 2,000.00");
        jPanel1.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 1250, -1, 50));

        jLabel90.setFont(new java.awt.Font("Perpetua", 2, 24)); // NOI18N
        jLabel90.setForeground(new java.awt.Color(255, 255, 255));
        jLabel90.setText("Php 2,000.00");
        jPanel1.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 1300, -1, 30));

        jLabel91.setFont(new java.awt.Font("Perpetua", 2, 24)); // NOI18N
        jLabel91.setForeground(new java.awt.Color(255, 255, 255));
        jLabel91.setText("Php 2,000.00");
        jPanel1.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 1340, -1, 30));

        jLabelSpa5.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabelSpa5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSpa5.setText(" SERVICES");
        jLabelSpa5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSpa5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSpa5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelSpa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 1370, 80, 50));

        jLabel92.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N
        jLabel92.setForeground(new java.awt.Color(255, 255, 255));
        jLabel92.setText("-- facial treatment --");
        jPanel1.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 1190, -1, 50));

        jLabel93.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(255, 255, 255));
        jLabel93.setText("Classical Facial");
        jPanel1.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 1240, -1, 50));

        jLabel94.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(255, 255, 255));
        jLabel94.setText("Hydrating Facial");
        jPanel1.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 1330, 150, 30));

        jLabel95.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(255, 255, 255));
        jLabel95.setText("Anti-Aging Facial");
        jPanel1.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 1290, -1, 30));

        jLabel96.setFont(new java.awt.Font("Perpetua", 2, 24)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(255, 255, 255));
        jLabel96.setText("Php 800.00");
        jPanel1.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 1240, -1, 50));

        jLabel97.setFont(new java.awt.Font("Perpetua", 2, 24)); // NOI18N
        jLabel97.setForeground(new java.awt.Color(255, 255, 255));
        jLabel97.setText("Php 1,000.00");
        jPanel1.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 1290, -1, 30));

        jLabel98.setFont(new java.awt.Font("Perpetua", 2, 24)); // NOI18N
        jLabel98.setForeground(new java.awt.Color(255, 255, 255));
        jLabel98.setText("Php 1,100.00");
        jPanel1.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 1330, -1, 30));

        jLabelSpa6.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabelSpa6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSpa6.setText(" SERVICES");
        jLabelSpa6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSpa6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSpa6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelSpa6, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 1350, 80, 50));

        jLabel99.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N
        jLabel99.setForeground(new java.awt.Color(255, 255, 255));
        jLabel99.setText("-- peeling treatments --");
        jPanel1.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1470, -1, 50));

        jLabel100.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel100.setForeground(new java.awt.Color(255, 255, 255));
        jLabel100.setText("Chemical Peel");
        jPanel1.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 1510, -1, 50));

        jLabel101.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel101.setForeground(new java.awt.Color(255, 255, 255));
        jLabel101.setText("Fruit-Acid Peel");
        jPanel1.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 1560, -1, 30));

        jLabel102.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(255, 255, 255));
        jLabel102.setText("Microdermabrasion");
        jPanel1.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 1600, 190, 30));

        jLabel103.setFont(new java.awt.Font("Perpetua", 2, 24)); // NOI18N
        jLabel103.setForeground(new java.awt.Color(255, 255, 255));
        jLabel103.setText("Php 1,200.00");
        jPanel1.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 1600, -1, 30));

        jLabel104.setFont(new java.awt.Font("Perpetua", 2, 24)); // NOI18N
        jLabel104.setForeground(new java.awt.Color(255, 255, 255));
        jLabel104.setText("Php 1,200.00");
        jPanel1.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 1560, -1, 30));

        jLabel105.setFont(new java.awt.Font("Perpetua", 2, 24)); // NOI18N
        jLabel105.setForeground(new java.awt.Color(255, 255, 255));
        jLabel105.setText("Php 1,500.00");
        jPanel1.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 1510, -1, 50));

        jLabelSpa7.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabelSpa7.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSpa7.setText(" SERVICES");
        jLabelSpa7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSpa7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSpa7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelSpa7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 1640, 80, 50));

        jLabel106.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N
        jLabel106.setForeground(new java.awt.Color(255, 255, 255));
        jLabel106.setText("-- waxing --");
        jPanel1.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 1460, -1, 50));

        jLabel107.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel107.setForeground(new java.awt.Color(255, 255, 255));
        jLabel107.setText("Eyebrow Shaping");
        jPanel1.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 1500, -1, 50));

        jLabel53.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Full Body Waxing");
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 1550, -1, 30));

        jLabel108.setFont(new java.awt.Font("Perpetua", 2, 24)); // NOI18N
        jLabel108.setForeground(new java.awt.Color(255, 255, 255));
        jLabel108.setText("Php 500.00");
        jPanel1.add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 1500, -1, 50));

        jLabel109.setFont(new java.awt.Font("Perpetua", 2, 24)); // NOI18N
        jLabel109.setForeground(new java.awt.Color(255, 255, 255));
        jLabel109.setText("Php 1,500.00");
        jPanel1.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 1550, -1, 30));

        jLabelSpa8.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabelSpa8.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSpa8.setText(" SERVICES");
        jLabelSpa8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSpa8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSpa8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelSpa8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 1590, 80, 50));

        NiggaBG3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/niggaa.jpg"))); // NOI18N
        jPanel1.add(NiggaBG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1150, 1360, 570));

        NiggaBG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/niggaa.jpg"))); // NOI18N
        jPanel1.add(NiggaBG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 1360, 590));

        NiggaBG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/niggaa.jpg"))); // NOI18N
        jPanel1.add(NiggaBG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1890, 1360, 270));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        background1.setText("jLabel1");
        jPanel1.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1140, 2040));

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        background2.setText("jLabel4");
        jPanel1.add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, -10, -1, -1));

        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        background3.setText("jLabel3");
        jPanel1.add(background3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 2040));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1494, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 2169, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelSpaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSpaMouseClicked
        Services ser = new Services();
        ser.setVisible(true);
        ser.pack();
        ser.setLocationRelativeTo(null);
        ser.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelSpaMouseClicked

    private void jLabelProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProductsMouseClicked
        Products prod = new Products();
        prod.setVisible(true);
        prod.pack();
        prod.setLocationRelativeTo(null);
        prod.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelProductsMouseClicked

    private void jLabelContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelContactMouseClicked
        /*Contact con = new Contact();
        con.setVisible(true);
        con.pack();
        con.setLocationRelativeTo(null);
        con.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();*/
    }//GEN-LAST:event_jLabelContactMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Admin ad = new Admin();
        ad.setVisible(true);
        ad.pack();
        ad.setLocationRelativeTo(null);
        ad.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabelAbout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAbout1MouseClicked
        About abt = new About();
        abt.setVisible(true);
        abt.pack();
        abt.setLocationRelativeTo(null);
        abt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelAbout1MouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        int close = JOptionPane.showConfirmDialog(null, "Are you sure you want to go back to the LOG IN page?", "Confirmation Box", JOptionPane.YES_NO_OPTION);

        if (close == JOptionPane.YES_OPTION) {
            Login usr = new Login();
            usr.setVisible(true);
            usr.pack();
            usr.setLocationRelativeTo(null);
            usr.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelSpa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSpa1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelSpa1MouseClicked

    private void jLabelSpa2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSpa2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelSpa2MouseClicked

    private void jLabelSpa3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSpa3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelSpa3MouseClicked

    private void jLabelSpa4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSpa4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelSpa4MouseClicked

    private void jLabelSpa5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSpa5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelSpa5MouseClicked

    private void jLabelSpa6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSpa6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelSpa6MouseClicked

    private void jLabelSpa7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSpa7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelSpa7MouseClicked

    private void jLabelSpa8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSpa8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelSpa8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserServices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NiggaBG1;
    private javax.swing.JLabel NiggaBG2;
    private javax.swing.JLabel NiggaBG3;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JLabel jLabelAbout1;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelContact;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelProducts;
    private javax.swing.JLabel jLabelSpa;
    private javax.swing.JLabel jLabelSpa1;
    private javax.swing.JLabel jLabelSpa2;
    private javax.swing.JLabel jLabelSpa3;
    private javax.swing.JLabel jLabelSpa4;
    private javax.swing.JLabel jLabelSpa5;
    private javax.swing.JLabel jLabelSpa6;
    private javax.swing.JLabel jLabelSpa7;
    private javax.swing.JLabel jLabelSpa8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
