/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontdesksystem;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User PC
 */
public class About extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    public About() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelSpa = new javax.swing.JLabel();
        jLabelProducts = new javax.swing.JLabel();
        jLabelContact = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelAbout1 = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        background2 = new javax.swing.JLabel();
        background3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabelSpa1 = new javax.swing.JLabel();
        jLabelProducts1 = new javax.swing.JLabel();
        jLabelContact1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelAbout2 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        NiggaBG1 = new javax.swing.JLabel();
        background4 = new javax.swing.JLabel();
        background5 = new javax.swing.JLabel();
        background6 = new javax.swing.JLabel();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("about us");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, 80));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0, 80));

        jLabelSpa.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabelSpa.setText(" SERVICES");
        jLabelSpa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSpa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSpaMouseClicked(evt);
            }
        });

        jLabelProducts.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabelProducts.setText("PRODUCTS");
        jLabelProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProductsMouseClicked(evt);
            }
        });

        jLabelContact.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabelContact.setText("CONTACT");
        jLabelContact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelContactMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\User PC\\Downloads\\Screenshot_2024-11-17_123822-removebg-preview (2).png")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabelAbout1.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabelAbout1.setText("ABOUT");
        jLabelAbout1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAbout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAbout1MouseClicked(evt);
            }
        });

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(94, 94, 94)
                .addComponent(jLabelAbout1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jLabelProducts)
                .addGap(55, 55, 55)
                .addComponent(jLabelSpa)
                .addGap(58, 58, 58)
                .addComponent(jLabelContact)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 589, Short.MAX_VALUE)
                .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClose)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAbout1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSpa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelContact, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelClose)
                            .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot_2024-11-17_123703-removebg-preview.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        background1.setText("jLabel1");
        jPanel2.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1150, 2040));

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 60, -1, -1));

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        background2.setText("jLabel4");
        jPanel2.add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        background3.setText("jLabel3");
        jPanel2.add(background3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane2.setViewportView(jPanel2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1380, 2329));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSpa1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabelSpa1.setText(" SERVICES");
        jLabelSpa1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSpa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSpa1MouseClicked(evt);
            }
        });
        jPanel4.add(jLabelSpa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, -10, 130, 50));

        jLabelProducts1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabelProducts1.setText("PRODUCTS");
        jLabelProducts1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelProducts1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProducts1MouseClicked(evt);
            }
        });
        jPanel4.add(jLabelProducts1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, -10, 130, 50));

        jLabelContact1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabelContact1.setText("CONTACT");
        jLabelContact1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelContact1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelContact1MouseClicked(evt);
            }
        });
        jPanel4.add(jLabelContact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, -10, 140, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot_2024-11-17_123822-removebg-preview (5).png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        jLabelAbout2.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabelAbout2.setForeground(new java.awt.Color(255, 0, 0));
        jLabelAbout2.setText("ABOUT");
        jLabelAbout2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAbout2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAbout2MouseClicked(evt);
            }
        });
        jPanel4.add(jLabelAbout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -10, 70, 50));

        jLabel47.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout (1).png"))); // NOI18N
        jLabel47.setText("Exit");
        jLabel47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel47MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 0, 50, 30));

        jLabel48.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel48.setText("BILL");
        jLabel48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel48MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, 60, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot_2024-11-17_123703-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Perpetua", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("our philosophy");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 1540, -1, 80));

        jLabel26.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Get Social");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2080, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_facebook (1).png"))); // NOI18N
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2120, -1, 30));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_instagram (1).png"))); // NOI18N
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2150, -1, 30));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_tiktok (1).png"))); // NOI18N
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2180, -1, 30));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_youtube.png"))); // NOI18N
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2210, -1, 30));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_twitter-sign (1).png"))); // NOI18N
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2240, -1, 30));

        jLabel21.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("VAN Salon and Spa");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 2120, -1, 30));

        jLabel33.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("vansalonandspa");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 2150, -1, 30));

        jLabel34.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("VSAS");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 2180, -1, 30));

        jLabel35.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("VANSalonAndSpa ");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 2210, -1, 30));

        jLabel36.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("VSAS");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 2240, -1, 30));

        jLabel22.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("© 2024 VAN Salon and Spa | All Rights Reserved | Privacy Policy | Terms & Conditions");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 2290, -1, -1));

        jLabel25.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Appointments@VANSalonAndSpa.com");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 2180, -1, 30));

        jLabel23.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("0912 345 6789");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 2150, -1, 40));

        jLabel45.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Brgy. Bucana, Nasugbu Batangas");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 2130, -1, 20));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_pin.png"))); // NOI18N
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 2120, -1, 30));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_call (1).png"))); // NOI18N
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 2150, -1, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_email2 (1).png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 2180, 30, 30));

        jLabel39.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText(" Contacts");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 2080, -1, -1));

        jLabel38.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Hours");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 2080, -1, -1));

        jLabel40.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Mon : 7:00 am - 8:00 pm");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 2110, -1, 40));

        jLabel41.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Tue : 7:00 am - 8:00 pm");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 2130, -1, 40));

        jLabel42.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Wed : 7:00 am - 8:00 pm");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 2160, -1, 20));

        jLabel43.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Thurs : 7:00 am - 8:00 pm");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 2180, -1, 20));

        jLabel44.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Fri : 7:00 am - 8:00 pm");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 2200, 160, 20));

        jLabel46.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Sat: 7:00 am - 8:00 pm");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 2220, 150, 20));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/462537887_580053814602662_2758245647023974022_n.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 2130, -1, -1));

        jLabel16.setFont(new java.awt.Font("Perpetua Titling MT", 1, 60)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("about us");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, -1, 80));

        jLabel53.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("collaboration between the three individuals who are dedicated to creating a");
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 640, 660, 70));

        jLabel57.setFont(new java.awt.Font("Perpetua", 0, 48)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("our space");
        jPanel1.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 940, -1, 80));

        jLabel54.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("what does VAN mean anyway?");
        jPanel1.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, -1, 80));

        jLabel55.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("VAN stands for the initials of the founders: Vince, Ariane, and Noreen. ");
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, 640, 70));

        jLabel56.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("unique and exceptional experience at the salon and spa. Each founder bring");
        jPanel1.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 670, 660, 70));

        jLabel59.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("of their shared vision to provide a space of beauty, relaxation, and wellness. ");
        jPanel1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 730, 670, 70));

        jLabel58.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("The name reflects a personal connection and symbolizes the unity and");
        jPanel1.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 620, 70));

        jLabel60.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("commitment to offering clients a transformative experience. Through VAN, ");
        jPanel1.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 790, 680, 60));

        jLabel61.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("their own expertise and passion to the business, making VAN a reflection");
        jPanel1.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 700, 650, 70));

        jLabel62.setFont(new java.awt.Font("Perpetua", 1, 28)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("personalized experience");
        jPanel1.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 1790, 290, 40));

        jLabel63.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("The name isn’t just an acronym; it represents trust, care, and a");
        jPanel1.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 760, 620, 70));

        jLabel66.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText(" the founders aim to create a welcoming environment where every client");
        jPanel1.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 810, 680, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/totengTV.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 520, -1, 250));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chukoyTV.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 620, -1, 250));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/norsKyub.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 480, -1, 250));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/interior5.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1290, 320, 180));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/interior.jpg"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 1060, -1, 410));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/interior6.jpg"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1060, 320, 200));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/interior4.jpg"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 1060, 320, 410));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_hand-mirror.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 1640, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_heart (2).png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 1650, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_beauty.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 1660, -1, -1));

        jLabel67.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("feels valued and pampered.");
        jPanel1.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 840, 620, 70));

        jLabel68.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("come and experience exceptional");
        jPanel1.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 1870, 300, 40));

        jLabel69.setFont(new java.awt.Font("Perpetua", 1, 28)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("we love what we do");
        jPanel1.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 1790, 240, 40));

        jLabel70.setFont(new java.awt.Font("Perpetua", 1, 28)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("professional care");
        jPanel1.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 1800, 210, 40));

        jLabel71.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("service.");
        jPanel1.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 1900, 70, 30));

        jLabel72.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("each guest is our favorite guest.");
        jPanel1.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 1840, -1, 40));

        jLabel73.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("people that you'll meet in our studio ");
        jPanel1.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(971, 1840, 330, 40));

        jLabel74.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("are doing job they love. come and ");
        jPanel1.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 1870, -1, 40));

        jLabel75.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("make sure there is a difference.");
        jPanel1.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 1900, 280, 40));

        jLabel76.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(255, 255, 255));
        jLabel76.setText("all products we use are professional  ");
        jPanel1.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1840, -1, 40));

        jLabel77.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(255, 255, 255));
        jLabel77.setText("and have proven efficiency.");
        jPanel1.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 1870, 240, 40));

        jLabel78.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(255, 255, 255));
        jLabel78.setText("No compromises.");
        jPanel1.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 1900, 160, 40));

        NiggaBG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/niggaa.jpg"))); // NOI18N
        jPanel1.add(NiggaBG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2040, 1360, 270));

        background4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        background4.setText("jLabel1");
        jPanel1.add(background4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1140, 2040));

        background5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        background5.setText("jLabel4");
        jPanel1.add(background5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, -20, -1, -1));

        background6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        background6.setText("jLabel3");
        jPanel1.add(background6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 2040));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int close = JOptionPane.showConfirmDialog(null, "Are you sure you want to go back to the MAIN MENU?", "Confirmation Box", JOptionPane.YES_NO_OPTION);

        if (close == JOptionPane.YES_OPTION) {
            User usr = new User();
            usr.setVisible(true);
            usr.pack();
            usr.setLocationRelativeTo(null);
            usr.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabelSpaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSpaMouseClicked
        Services ser = new Services();
        ser.setVisible(true);
        ser.pack();
        ser.setLocationRelativeTo(null);
        ser.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelSpaMouseClicked

    private void jLabelProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProductsMouseClicked
        Products prod = new Products();
        prod.setVisible(true);
        prod.pack();
        prod.setLocationRelativeTo(null);
        prod.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelProductsMouseClicked

    private void jLabelContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelContactMouseClicked
        /*Contact con = new Contact();
        con.setVisible(true);
        con.pack();
        con.setLocationRelativeTo(null);
        con.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();*/
    }//GEN-LAST:event_jLabelContactMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Admin ad = new Admin();
        ad.setVisible(true);
        ad.pack();
        ad.setLocationRelativeTo(null);
        ad.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabelAbout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAbout1MouseClicked
        About abt = new About();
        abt.setVisible(true);
        abt.pack();
        abt.setLocationRelativeTo(null);
        abt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelAbout1MouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        int close = JOptionPane.showConfirmDialog(null, "Are you sure you want to go back to the LOG IN page?", "Confirmation Box", JOptionPane.YES_NO_OPTION);

        if (close == JOptionPane.YES_OPTION) {
            Login usr = new Login();
            usr.setVisible(true);
            usr.pack();
            usr.setLocationRelativeTo(null);
            usr.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelSpa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSpa1MouseClicked
        UserServices us = new UserServices();
        us.setVisible(true);
        us.pack();
        us.setLocationRelativeTo(null);
        us.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelSpa1MouseClicked

    private void jLabelProducts1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProducts1MouseClicked
        UserProduct up = new UserProduct();
        up.setVisible(true);
        up.pack();
        up.setLocationRelativeTo(null);
        up.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelProducts1MouseClicked

    private void jLabelContact1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelContact1MouseClicked
        Contacts con = new Contacts();
        con.setVisible(true);
        con.pack();
        con.setLocationRelativeTo(null);
        con.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelContact1MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        User use = new User();
        use.setVisible(true);
        use.pack();
        use.setLocationRelativeTo(null);
        use.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabelAbout2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAbout2MouseClicked
        About abt = new About();
        abt.setVisible(true);
        abt.pack();
        abt.setLocationRelativeTo(null);
        abt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelAbout2MouseClicked

    private void jLabel47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel47MouseClicked
        Login lgf = new Login();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel47MouseClicked

    private void jLabel48MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel48MouseClicked
        Bill bi= new Bill();
        bi.setVisible(true);
        bi.pack();
        bi.setLocationRelativeTo(null);
        bi.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel48MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NiggaBG1;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JLabel background4;
    private javax.swing.JLabel background5;
    private javax.swing.JLabel background6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAbout1;
    private javax.swing.JLabel jLabelAbout2;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelContact;
    private javax.swing.JLabel jLabelContact1;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelProducts;
    private javax.swing.JLabel jLabelProducts1;
    private javax.swing.JLabel jLabelSpa;
    private javax.swing.JLabel jLabelSpa1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
