/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontdesksystem;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User PC
 */
public class Contacts extends javax.swing.JFrame {

    /**
     * Creates new form Contacts
     */
    public Contacts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelSpa = new javax.swing.JLabel();
        jLabelProducts = new javax.swing.JLabel();
        jLabelContact = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelAbout1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NiggaBG1 = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();
        background3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1380, 2329));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSpa.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabelSpa.setText(" SERVICES");
        jLabelSpa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSpa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSpaMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelSpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, -10, 130, 50));

        jLabelProducts.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabelProducts.setText("PRODUCTS");
        jLabelProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProductsMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, -10, 130, 50));

        jLabelContact.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabelContact.setForeground(new java.awt.Color(255, 0, 0));
        jLabelContact.setText("CONTACT");
        jLabelContact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelContactMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, -10, 140, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot_2024-11-17_123822-removebg-preview (5).png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        jLabelAbout1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabelAbout1.setText("ABOUT");
        jLabelAbout1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAbout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAbout1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabelAbout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -10, 70, 50));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout (1).png"))); // NOI18N
        jLabel5.setText("Exit");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 0, 50, 30));

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel9.setText("BILL");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, 60, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot_2024-11-17_123703-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, -1));

        jLabel26.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Get Social");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1580, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_facebook (1).png"))); // NOI18N
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1620, -1, 30));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_instagram (1).png"))); // NOI18N
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1650, -1, 30));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_tiktok (1).png"))); // NOI18N
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1680, -1, 30));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_youtube.png"))); // NOI18N
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1710, -1, 30));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_twitter-sign (1).png"))); // NOI18N
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1740, -1, 30));

        jLabel21.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("VAN Salon and Spa");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1620, -1, 30));

        jLabel33.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("vansalonandspa");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1650, -1, 30));

        jLabel34.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("VSAS");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1680, -1, 30));

        jLabel35.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("VANSalonAndSpa ");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1710, -1, 30));

        jLabel36.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("VSAS");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1740, -1, 30));

        jLabel22.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("© 2024 VAN Salon and Spa | All Rights Reserved | Privacy Policy | Terms & Conditions");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 1790, -1, -1));

        jLabel25.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Appointments@VANSalonAndSpa.com");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 1680, -1, 30));

        jLabel23.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("0912 345 6789");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 1650, -1, 40));

        jLabel45.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Brgy. Bucana, Nasugbu Batangas");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 1630, -1, 20));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_pin.png"))); // NOI18N
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 1620, -1, 30));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_call (1).png"))); // NOI18N
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 1650, -1, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_email2 (1).png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 1680, 30, 30));

        jLabel39.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText(" Contacts");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 1580, -1, -1));

        jLabel38.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Hours");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 1580, -1, -1));

        jLabel40.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Mon : 7:00 am - 8:00 pm");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 1610, -1, 40));

        jLabel41.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Tue : 7:00 am - 8:00 pm");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 1630, -1, 40));

        jLabel42.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Wed : 7:00 am - 8:00 pm");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 1660, -1, 20));

        jLabel43.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Thurs : 7:00 am - 8:00 pm");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 1680, -1, 20));

        jLabel44.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Fri : 7:00 am - 8:00 pm");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 1700, 160, 20));

        jLabel46.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Sat: 7:00 am - 8:00 pm");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 1720, 150, 20));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/462537887_580053814602662_2758245647023974022_n.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 1630, -1, -1));

        jLabel14.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("get in touch");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, -1, 60));

        jLabel52.setFont(new java.awt.Font("Perpetua", 1, 48)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Personalized Care in our Urban ");
        jPanel1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, -1, 80));

        jLabel87.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel87.setForeground(new java.awt.Color(255, 255, 255));
        jLabel87.setText("complimentary consultation so that we can meet your individual needs.");
        jPanel1.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 660, 930, 30));

        jLabel47.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Phone");
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 1340, -1, -1));

        jLabel24.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("VAN Salon and Spa");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1160, 180, -1));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_facebook (1).png"))); // NOI18N
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1160, 80, -1));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_instagram (1).png"))); // NOI18N
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1190, 80, -1));

        jLabel50.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("VSAS");
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1220, 90, -1));

        jLabel51.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("vansalonandspa");
        jPanel1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1190, 150, -1));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_tiktok (1).png"))); // NOI18N
        jPanel1.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1220, 80, -1));

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_youtube.png"))); // NOI18N
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1250, 80, -1));

        jLabel56.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("VANSalonAndSpa ");
        jPanel1.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1250, 180, -1));

        jLabel57.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("VSAS");
        jPanel1.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1280, 90, -1));

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_twitter-sign (1).png"))); // NOI18N
        jPanel1.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1280, 80, -1));

        jLabel59.setFont(new java.awt.Font("Perpetua", 1, 48)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Sanctuary");
        jPanel1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, -1, 80));

        jLabel60.setFont(new java.awt.Font("Perpetua", 1, 48)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Stay Looking Your Best With");
        jPanel1.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, 80));

        jLabel110.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel110.setForeground(new java.awt.Color(255, 255, 255));
        jLabel110.setText("VAN Salon And Spa tailors its treatments for each client. Book you appointments now or schedule your ");
        jPanel1.add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 630, 930, 30));

        jLabel61.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("Address");
        jPanel1.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 760, -1, -1));

        jLabel62.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("Brgy. Bucana, Nasugbu Batangas");
        jPanel1.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 790, -1, 30));

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_pin.png"))); // NOI18N
        jPanel1.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 790, -1, 30));

        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_email2 (1).png"))); // NOI18N
        jPanel1.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 830, 30, 30));

        jLabel65.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("Appointments@VANSalonAndSpa.com");
        jPanel1.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 830, -1, 30));

        jLabel66.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("Hours");
        jPanel1.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 910, -1, -1));

        jLabel67.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("Mon : 7:00 am - 8:00 pm");
        jPanel1.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 940, -1, 40));

        jLabel68.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Tue : 7:00 am - 8:00 pm");
        jPanel1.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 960, -1, 40));

        jLabel69.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("Wed : 7:00 am - 8:00 pm");
        jPanel1.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 990, -1, 20));

        jLabel70.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("Thurs : 7:00 am - 8:00 pm");
        jPanel1.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1010, -1, 20));

        jLabel71.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Fri : 7:00 am - 8:00 pm");
        jPanel1.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1030, 220, 20));

        jLabel72.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("Sun: CLOSED");
        jPanel1.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1070, 150, 20));

        jLabel73.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("Sat: 7:00 am - 8:00 pm");
        jPanel1.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1050, 210, 20));

        jLabel53.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Get Social");
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 1130, -1, -1));

        jLabel74.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("0912 345 6789");
        jPanel1.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1380, -1, 40));

        jLabel75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_call (1).png"))); // NOI18N
        jPanel1.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1380, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exterior.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 760, 550, 600));

        NiggaBG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/niggaa.jpg"))); // NOI18N
        jPanel1.add(NiggaBG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1540, 1360, 280));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        background1.setText("jLabel1");
        jPanel1.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1140, 1820));

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        background2.setText("jLabel4");
        jPanel1.add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, 1820));

        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        background3.setText("jLabel3");
        jPanel1.add(background3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1820));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1368, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1831, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelSpaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSpaMouseClicked
        UserServices us = new UserServices();
        us.setVisible(true);
        us.pack();
        us.setLocationRelativeTo(null);
        us.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelSpaMouseClicked

    private void jLabelProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProductsMouseClicked
        UserProduct up = new UserProduct();
        up.setVisible(true);
        up.pack();
        up.setLocationRelativeTo(null);
        up.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelProductsMouseClicked

    private void jLabelContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelContactMouseClicked
        Contacts con = new Contacts();
        con.setVisible(true);
        con.pack();
        con.setLocationRelativeTo(null);
        con.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelContactMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        User use = new User();
        use.setVisible(true);
        use.pack();
        use.setLocationRelativeTo(null);
        use.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabelAbout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAbout1MouseClicked
        About abt = new About();
        abt.setVisible(true);
        abt.pack();
        abt.setLocationRelativeTo(null);
        abt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelAbout1MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Login lgf = new Login();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        Bill bi= new Bill();
        bi.setVisible(true);
        bi.pack();
        bi.setLocationRelativeTo(null);
        bi.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contacts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NiggaBG1;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAbout1;
    private javax.swing.JLabel jLabelContact;
    private javax.swing.JLabel jLabelProducts;
    private javax.swing.JLabel jLabelSpa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
