/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontdesksystem;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User PC
 */
public class User extends javax.swing.JFrame {

    /**
     * Creates new form UserHomepage
     */
    public User() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelSpa = new javax.swing.JLabel();
        jLabelProducts = new javax.swing.JLabel();
        jLabelContact = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelAbout1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabelSpa10 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabelSpa11 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabelSpa12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelProducts5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NiggaBG1 = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();
        background3 = new javax.swing.JLabel();
        jLabelSpa5 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabelSpa8 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabelSpa6 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabelSpa7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabelProducts3 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabelProducts2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1380, 2329));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSpa.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabelSpa.setText(" SERVICES");
        jLabelSpa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSpa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSpaMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelSpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, -10, 130, 50));

        jLabelProducts.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabelProducts.setText("PRODUCTS");
        jLabelProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProductsMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, -10, 130, 50));

        jLabelContact.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabelContact.setText("CONTACT");
        jLabelContact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelContactMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, -10, 140, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot_2024-11-17_123822-removebg-preview (5).png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        jLabelAbout1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabelAbout1.setText("ABOUT");
        jLabelAbout1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAbout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAbout1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabelAbout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, -10, 70, 50));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout (1).png"))); // NOI18N
        jLabel2.setText("Exit");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 0, 50, 30));

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel9.setText("BILL");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 60, 30));

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/feedback (1).png"))); // NOI18N
        jLabel10.setText("FEEDBACK");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 140, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot_2024-11-17_123703-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        jLabel26.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Get Social");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1930, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_facebook (1).png"))); // NOI18N
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1970, -1, 30));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_instagram (1).png"))); // NOI18N
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2000, -1, 30));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_tiktok (1).png"))); // NOI18N
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2030, -1, 30));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_youtube.png"))); // NOI18N
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2060, -1, 30));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_twitter-sign (1).png"))); // NOI18N
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2090, -1, 30));

        jLabel21.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("VAN Salon and Spa");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1970, -1, 30));

        jLabel33.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("vansalonandspa");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 2000, -1, 30));

        jLabel34.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("VSAS");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 2030, -1, 30));

        jLabel35.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("VANSalonAndSpa ");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 2060, -1, 30));

        jLabel36.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("VSAS");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 2090, -1, 30));

        jLabel22.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("© 2024 VAN Salon and Spa | All Rights Reserved | Privacy Policy | Terms & Conditions");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 2140, -1, -1));

        jLabel25.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Appointments@VANSalonAndSpa.com");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 2030, -1, 30));

        jLabel23.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("0912 345 6789");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 2000, -1, 40));

        jLabel45.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Brgy. Bucana, Nasugbu Batangas");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 1980, -1, 20));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_pin.png"))); // NOI18N
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 1970, -1, 30));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_call (1).png"))); // NOI18N
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 2000, -1, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pi7_email2 (1).png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 2030, 30, 30));

        jLabel39.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText(" Contacts");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 1930, -1, -1));

        jLabel38.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Hours");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 1930, -1, -1));

        jLabel40.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Mon : 7:00 am - 8:00 pm");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 1960, -1, 40));

        jLabel41.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Tue : 7:00 am - 8:00 pm");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 1980, -1, 40));

        jLabel42.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Wed : 7:00 am - 8:00 pm");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 2010, -1, 20));

        jLabel43.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Thurs : 7:00 am - 8:00 pm");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 2030, -1, 20));

        jLabel44.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Fri : 7:00 am - 8:00 pm");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 2050, 160, 20));

        jLabel46.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Sat: 7:00 am - 8:00 pm");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 2070, 150, 20));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/462537887_580053814602662_2758245647023974022_n.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 1980, -1, -1));

        jLabel14.setFont(new java.awt.Font("Perpetua Titling MT", 1, 60)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Salon and spa");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, -1, 80));

        jLabel60.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("welcome to VAN salon and spa");
        jPanel1.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, -1, 80));

        jLabel76.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(255, 255, 255));
        jLabel76.setText("Our team does not change from month-to-month so our");
        jPanel1.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 680, -1, 40));

        jLabel81.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(255, 255, 255));
        jLabel81.setText("We believe in consistency. ");
        jPanel1.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 650, -1, 40));

        jLabel79.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(255, 255, 255));
        jLabel79.setText("customers can build long-term relationship with people");
        jPanel1.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 710, -1, 40));

        jLabel80.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setText("they trust.");
        jPanel1.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 740, -1, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nagssprayNgHairNaGirl_1.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, -1, 350));

        jLabel56.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("WE OFFER");
        jPanel1.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 890, -1, 100));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hairlalu.jpg"))); // NOI18N
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 1000, -1, 360));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kukoYarn.jpg"))); // NOI18N
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 1000, -1, 360));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/massahe.jpg"))); // NOI18N
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 1000, -1, 360));

        jLabel62.setFont(new java.awt.Font("Perpetua", 0, 48)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("spa");
        jPanel1.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 1350, -1, 50));

        jLabelSpa10.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabelSpa10.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSpa10.setText(" SERVICES");
        jLabelSpa10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSpa10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSpa10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelSpa10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 1390, 110, 50));

        jLabel63.setFont(new java.awt.Font("Perpetua", 0, 48)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("nail");
        jPanel1.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 1350, -1, 70));

        jLabelSpa11.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabelSpa11.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSpa11.setText(" SERVICES");
        jLabelSpa11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSpa11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSpa11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelSpa11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 1390, 130, 50));

        jLabel64.setFont(new java.awt.Font("Perpetua", 0, 48)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("hair");
        jPanel1.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 1350, -1, 60));

        jLabelSpa12.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabelSpa12.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSpa12.setText(" SERVICES");
        jLabelSpa12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSpa12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSpa12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelSpa12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 1390, 110, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/products.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 1480, 400, 320));

        jLabel65.setFont(new java.awt.Font("Perpetua", 0, 16)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("get that fresh-out-of-the-salon feeling - from home.");
        jPanel1.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 1520, 320, 30));

        jLabel66.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("SHOP");
        jPanel1.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 1530, -1, 80));

        jLabel83.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(255, 255, 255));
        jLabel83.setText("At VAN Salon and Spa, we believe in offering only the finest  that align");
        jPanel1.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 1600, -1, 20));

        jLabel90.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel90.setForeground(new java.awt.Color(255, 255, 255));
        jLabel90.setText(" that align with our philosophy of beauty, relaxation, and wellness. Our ");
        jPanel1.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 1630, -1, 20));

        jLabel91.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel91.setForeground(new java.awt.Color(255, 255, 255));
        jLabel91.setText("carefully curated  selection is designed to cater to all your self-care needs, ");
        jPanel1.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 1660, -1, 20));

        jLabel92.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel92.setForeground(new java.awt.Color(255, 255, 255));
        jLabel92.setText(" from rejuvenating skin care to luxurious hair treatments and everything in ");
        jPanel1.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 1690, 660, 20));

        jLabel93.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(255, 255, 255));
        jLabel93.setText(" between. Each product  is handpicked to ensure that it meets our high  ");
        jPanel1.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 1720, 690, 20));

        jLabel94.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(255, 255, 255));
        jLabel94.setText("standards of quality, purity, and effectiveness.");
        jPanel1.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 1740, 410, 30));

        jLabel7.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SERVICES");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 920, -1, -1));

        jLabelProducts5.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabelProducts5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProducts5.setText("PRODUCTS");
        jLabelProducts5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelProducts5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProducts5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelProducts5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 1800, 120, 40));

        jLabel6.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PRODUCTS");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 1550, -1, -1));

        NiggaBG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/niggaa.jpg"))); // NOI18N
        jPanel1.add(NiggaBG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1890, 1360, 270));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        background1.setText("jLabel1");
        jPanel1.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1140, 2040));

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        background2.setText("jLabel4");
        jPanel1.add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, -10, -1, -1));

        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        background3.setText("jLabel3");
        jPanel1.add(background3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 2040));

        jLabelSpa5.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        jLabelSpa5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSpa5.setText(" SERVICES");
        jLabelSpa5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSpa5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSpa5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelSpa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 930, 240, 60));

        jLabel55.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("WE OFFER");
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 920, -1, 80));

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hairlalu.jpg"))); // NOI18N
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 1030, -1, 360));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kukoYarn.jpg"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 1030, -1, 360));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/massahe.jpg"))); // NOI18N
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 1030, -1, 360));

        jLabel59.setFont(new java.awt.Font("Perpetua", 0, 48)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("spa");
        jPanel1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 1390, -1, 50));

        jLabelSpa8.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabelSpa8.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSpa8.setText(" SERVICES");
        jLabelSpa8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSpa8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSpa8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelSpa8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 1420, 110, 50));

        jLabel58.setFont(new java.awt.Font("Perpetua", 0, 48)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("nail");
        jPanel1.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 1380, -1, 70));

        jLabelSpa6.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabelSpa6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSpa6.setText(" SERVICES");
        jLabelSpa6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSpa6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSpa6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelSpa6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 1420, 130, 50));

        jLabel57.setFont(new java.awt.Font("Perpetua", 0, 48)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("hair");
        jPanel1.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 1380, -1, 60));

        jLabelSpa7.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabelSpa7.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSpa7.setText(" SERVICES");
        jLabelSpa7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSpa7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSpa7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelSpa7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 1420, 120, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/products.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1550, 400, 320));

        jLabel61.setFont(new java.awt.Font("Perpetua", 0, 16)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("get that fresh-out-of-the-salon feeling - from home.");
        jPanel1.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 1590, 320, 30));

        jLabelProducts3.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        jLabelProducts3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProducts3.setText("PRODUCTS");
        jLabelProducts3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelProducts3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProducts3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelProducts3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 1610, 190, 60));

        jLabel54.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("SHOP");
        jPanel1.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 1600, -1, 80));

        jLabel82.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(255, 255, 255));
        jLabel82.setText("At VAN Salon and Spa, we believe in offering only the finest  that align");
        jPanel1.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 1670, -1, 20));

        jLabel86.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(255, 255, 255));
        jLabel86.setText(" that align with our philosophy of beauty, relaxation, and wellness. Our ");
        jPanel1.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 1700, -1, 20));

        jLabel88.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(255, 255, 255));
        jLabel88.setText("carefully curated  selection is designed to cater to all your self-care needs, ");
        jPanel1.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 1730, -1, 20));

        jLabel89.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel89.setForeground(new java.awt.Color(255, 255, 255));
        jLabel89.setText(" from rejuvenating skin care to luxurious hair treatments and everything in ");
        jPanel1.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 1760, 660, 20));

        jLabel85.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(255, 255, 255));
        jLabel85.setText(" between. Each product  is handpicked to ensure that it meets our high  ");
        jPanel1.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 1790, 690, 20));

        jLabel87.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel87.setForeground(new java.awt.Color(255, 255, 255));
        jLabel87.setText("standards of quality, purity, and effectiveness.");
        jPanel1.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 1810, 400, 30));

        jLabelProducts2.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabelProducts2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProducts2.setText("PRODUCTS");
        jLabelProducts2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelProducts2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProducts2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelProducts2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 1870, 120, 40));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1454, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 2169, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelSpaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSpaMouseClicked
        UserServices us = new UserServices();
        us.setVisible(true);
        us.pack();
        us.setLocationRelativeTo(null);
        us.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelSpaMouseClicked

    private void jLabelProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProductsMouseClicked
        UserProduct up = new UserProduct();
        up.setVisible(true);
        up.pack();
        up.setLocationRelativeTo(null);
        up.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelProductsMouseClicked

    private void jLabelContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelContactMouseClicked
        Contacts con = new Contacts();
        con.setVisible(true);
        con.pack();
        con.setLocationRelativeTo(null);
        con.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelContactMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        User use = new User();
        use.setVisible(true);
        use.pack();
        use.setLocationRelativeTo(null);
        use.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabelAbout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAbout1MouseClicked
        About abt = new About();
        abt.setVisible(true);
        abt.pack();
        abt.setLocationRelativeTo(null);
        abt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelAbout1MouseClicked

    private void jLabelSpa5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSpa5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelSpa5MouseClicked

    private void jLabelSpa8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSpa8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelSpa8MouseClicked

    private void jLabelSpa6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSpa6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelSpa6MouseClicked

    private void jLabelSpa7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSpa7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelSpa7MouseClicked

    private void jLabelProducts3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProducts3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelProducts3MouseClicked

    private void jLabelProducts2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProducts2MouseClicked
        Products prod = new Products();
        prod.setVisible(true);
        prod.pack();
        prod.setLocationRelativeTo(null);
        prod.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelProducts2MouseClicked

    private void jLabelSpa10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSpa10MouseClicked
        Services ser = new Services();
        ser.setVisible(true);
        ser.pack();
        ser.setLocationRelativeTo(null);
        ser.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelSpa10MouseClicked

    private void jLabelSpa11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSpa11MouseClicked
        Services ser = new Services();
        ser.setVisible(true);
        ser.pack();
        ser.setLocationRelativeTo(null);
        ser.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelSpa11MouseClicked

    private void jLabelSpa12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSpa12MouseClicked
        Services ser = new Services();
        ser.setVisible(true);
        ser.pack();
        ser.setLocationRelativeTo(null);
        ser.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelSpa12MouseClicked

    private void jLabelProducts5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProducts5MouseClicked
        Products pro = new Products();
        pro.setVisible(true);
        pro.pack();
        pro.setLocationRelativeTo(null);
        pro.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelProducts5MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Login lgf = new Login();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        Bill bi= new Bill();
        bi.setVisible(true);
        bi.pack();
        bi.setLocationRelativeTo(null);
        bi.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        Feedback fb= new Feedback();
        fb.setVisible(true);
        fb.pack();
        fb.setLocationRelativeTo(null);
        fb.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NiggaBG1;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabelAbout1;
    private javax.swing.JLabel jLabelContact;
    private javax.swing.JLabel jLabelProducts;
    private javax.swing.JLabel jLabelProducts2;
    private javax.swing.JLabel jLabelProducts3;
    private javax.swing.JLabel jLabelProducts5;
    private javax.swing.JLabel jLabelSpa;
    private javax.swing.JLabel jLabelSpa10;
    private javax.swing.JLabel jLabelSpa11;
    private javax.swing.JLabel jLabelSpa12;
    private javax.swing.JLabel jLabelSpa5;
    private javax.swing.JLabel jLabelSpa6;
    private javax.swing.JLabel jLabelSpa7;
    private javax.swing.JLabel jLabelSpa8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
