/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontdesksystem;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.Set;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;


/**
 *
 * @author User PC
 */
public class Services extends javax.swing.JFrame {

    /**
     * Creates new form SpaServices
     */
    public Services() {
        initComponents();
        connectToDatabase();
        updateCombo();

    }
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    private void connectToDatabase() {
        try {
            // Load and register MySQL JDBC driver
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            // Establish connection to the database
            String url = "jdbc:mysql://localhost:3306/java_user_database"; // Replace with your database URL
            String username = "root"; // Replace with your username if necessary
            String password = ""; // Replace with your password if necessary
            con = DriverManager.getConnection(url, username, password);
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to connect to the database.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void updateCombo() {
    String sql = "SELECT * FROM services";
    Set<String> addedServices = new HashSet<>();  // Use a Set to store services and prevent duplicates
    
    try {
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();
        
        // Loop through the result set and add unique ServicesName to the combo box
        while (rs.next()) {
            String service = rs.getString("ServicesName");
            
            // Check if the service has already been added (using the Set to check for duplicates)
            if (!addedServices.contains(service)) {
                SpaComboBox.addItem(service);  // Add the service name to the combo box
                addedServices.add(service);  // Mark the service as added
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading categories.", "Error", JOptionPane.ERROR_MESSAGE);
    } finally {
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}


    
 
// Helper method to check if a service name already exists in the combo box
private boolean isServiceNameInComboBox(String serviceName) {
    for (int i = 0; i < SpaComboBox.getItemCount(); i++) {
        if (SpaComboBox.getItemAt(i).equals(serviceName)) {
            return true; // Return true if the service name is already in the combo box
        }
    }
    return false; // Return false if the service name is not in the combo box
}
    // Assuming you have a JComboBox named jComboBoxCat for selecting categories
// And a JTable named ServicesTable to display the services



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SpaComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ServicesTable = new javax.swing.JTable();
        Fillter = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ServiceName = new javax.swing.JTextField();
        ServicePrice = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ServicesTextArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        avail = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Search = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        getContentPane().add(SpaComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 240, 30));

        ServicesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ServicesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ServicesTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ServicesTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 362, 141));

        Fillter.setText("Filter");
        Fillter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FillterActionPerformed(evt);
            }
        });
        getContentPane().add(Fillter, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel3.setText("Price");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));
        getContentPane().add(ServiceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 310, 31));
        getContentPane().add(ServicePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 310, 30));

        Add.setText("ADD");
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
        });
        getContentPane().add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, 24));

        ServicesTextArea.setColumns(20);
        ServicesTextArea.setRows(5);
        jScrollPane2.setViewportView(ServicesTextArea);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 530, 330));

        jLabel5.setText("Kind of Service");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        Total.setText("Total :");
        getContentPane().add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 110, 40));

        avail.setText("Avail This Services");
        avail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                availMouseClicked(evt);
            }
        });
        getContentPane().add(avail, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 460, -1, -1));

        Delete.setText("DELETE");
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        Search.setText("SEARCH");
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMouseClicked(evt);
            }
        });
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FillterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FillterActionPerformed
        try {
        String selectedCategory = (String)SpaComboBox.getSelectedItem();

        if (selectedCategory == null || selectedCategory.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a category.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String query = "SELECT * FROM services WHERE ServicesName = ?";

        pst = con.prepareStatement(query);
        pst.setString(1, selectedCategory);  
        rs = pst.executeQuery();
        ResultSetMetaData rss = rs.getMetaData();
        int columnCount = rss.getColumnCount();
        DefaultTableModel df = (DefaultTableModel) ServicesTable.getModel();


        df.setRowCount(0);

        while (rs.next()) {
            Vector<Object> row = new Vector<>();

            row.add(rs.getString("Name"));
            row.add(rs.getBigDecimal("Price"));
           

            df.addRow(row);
        }
    } catch (SQLException ex) {
        Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Error fetching data from the database.", "Database Error", JOptionPane.ERROR_MESSAGE);
    }                           
    }//GEN-LAST:event_FillterActionPerformed

    private void ServicesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServicesTableMouseClicked
        int row = ServicesTable.getSelectedRow();
    if (row != -1) {
        String productName = ServicesTable.getValueAt(row, 0).toString();
        String productPrice = ServicesTable.getValueAt(row, 1).toString();
        ServiceName.setText(productName);
        ServicePrice.setText(productPrice);
    }
    }//GEN-LAST:event_ServicesTableMouseClicked
    double totalAmount = 0.0;
    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
         // Get the name and price from the text fields
    String serviceName = ServiceName.getText();  // Assuming ServiceName is the text field for service name
    String servicePriceText = ServicePrice.getText();  // Assuming ServicePrice is the text field for service price
    
    // Validate the input
    if (serviceName.isEmpty() || servicePriceText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter both service name and price.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Convert the price to a double
    double servicePrice;
    try {
        servicePrice = Double.parseDouble(servicePriceText);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid price.", "Invalid Price", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Create the service details text
    String serviceDetails = "Service Name: " + serviceName + "\n" +
                            "Service Price: " + servicePrice + "\n\n";
    
    // Append the service details to the ServicesTextArea
    ServicesTextArea.append(serviceDetails);
    
    // Add the service price to the total amount
    totalAmount += servicePrice;

    // Update the Total text field with the running total
    Total.setText("Total: " + totalAmount);  // Assuming Total is the text field for the total amount
    
    // Optional: Clear the text fields after adding
    ServiceName.setText("");  
    ServicePrice.setText("");
    
    // Insert the service details into the database
    String query = "INSERT INTO availservices (servicename, serviceprice) VALUES (?, ?)";
    
    try {
        // Prepare the SQL statement
        pst = con.prepareStatement(query);
        pst.setString(1, serviceName);  // Set the service name in the query
        pst.setDouble(2, servicePrice);  // Set the service price in the query
        
        // Execute the insert query
        int rowsAffected = pst.executeUpdate();
        
        if (rowsAffected > 0) {
            // If insertion is successful, show a success message
            JOptionPane.showMessageDialog(this, "Service added successfully to the database!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // If insertion fails
            JOptionPane.showMessageDialog(this, "Failed to add service to the database.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_AddMouseClicked

    private void availMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_availMouseClicked
        InfotoAvail ita = new InfotoAvail();
        ita.setVisible(true);
        ita.pack();
        ita.setLocationRelativeTo(null);
        ita.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_availMouseClicked

    private void SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseClicked
        // Get the service name from the input field
    String serviceName = ServiceName.getText();  // Assuming ServiceName is the text field for service name
    
    // Validate that the service name is not empty
    if (serviceName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a service name to search.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // SQL query to search for the price of the service based on the service name
    String query = "SELECT serviceprice FROM availservices WHERE servicename = ?";
    
    try {
        // Prepare the SQL statement
        pst = con.prepareStatement(query);
        pst.setString(1, serviceName);  // Set the service name in the query
        
        // Execute the query and get the result
        rs = pst.executeQuery();
        
        // If a record is found
        if (rs.next()) {
            // Get the service price from the result set
            double servicePrice = rs.getDouble("serviceprice");
            
            // Display the price in the relevant text field or label (assuming a text field named ServicePrice)
            ServicePrice.setText(String.valueOf(servicePrice));  // Assuming ServicePrice is the text field for service price
            
            // Optional: Display a success message
            JOptionPane.showMessageDialog(this, "Service found! Price: " + servicePrice, "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // If no matching service is found
            JOptionPane.showMessageDialog(this, "Service not found!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_SearchMouseClicked

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
       // Get the service name and price from the input fields
    String serviceName = ServiceName.getText();  // Assuming ServiceName is the text field for service name
    String servicePrice = ServicePrice.getText();  // Assuming ServicePrice is the text field for service price  
    
    // Validate that the service name and price are not empty
    if (serviceName.isEmpty() || servicePrice.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter both service name and price to delete.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // SQL query to delete the service based on the service name
    String query = "DELETE FROM availservices WHERE servicename = ? AND serviceprice = ?";
    
    try {
        // Prepare the SQL statement
        pst = con.prepareStatement(query);
        pst.setString(1, serviceName);  // Set the service name in the query
        pst.setString(2, servicePrice); // Set the service price in the query
        
        // Execute the update (delete)
        int rowsAffected = pst.executeUpdate();
        
        // Check if the service was deleted
        if (rowsAffected > 0) {
            // Service successfully deleted
            JOptionPane.showMessageDialog(this, "Service deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            
            // Now delete the specific entry from ServicesTextArea
            String currentText = ServicesTextArea.getText(); // Get the current content of the TextArea
            
            // Find the line that contains both the service name and service price
            String[] lines = currentText.split("\n");
            StringBuilder updatedText = new StringBuilder();
            
            // Loop through each line and append it to the updatedText except the one containing both the service name and service price
            for (String line : lines) {
                // Check if the line contains both the service name and service price
                if (!(line.contains(serviceName) && line.contains(servicePrice))) {
                    updatedText.append(line).append("\n");  // Add the line to the updatedText if it doesn't contain both
                }
            }
            
            // Set the updated content back to the ServicesTextArea
            ServicesTextArea.setText(updatedText.toString());
        } else {
            // If no record was deleted (service name and price not found)
            JOptionPane.showMessageDialog(this, "Service not found!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        // Clear the input fields after deletion
        ServiceName.setText("");  // Clear the ServiceName text field
        ServicePrice.setText("");  // Clear the ServicePrice text field

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_DeleteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Services().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Fillter;
    private javax.swing.JButton Search;
    private javax.swing.JTextField ServiceName;
    private javax.swing.JTextField ServicePrice;
    private javax.swing.JTable ServicesTable;
    private javax.swing.JTextArea ServicesTextArea;
    private javax.swing.JComboBox<String> SpaComboBox;
    private javax.swing.JLabel Total;
    private javax.swing.JButton avail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
