/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package homepage.design;

/**
 *
 * @author Noreen Grace G
 */
public class OurProducts extends javax.swing.JFrame {

    /**
     * Creates new form OurProducts
     */
    public OurProducts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Home = new javax.swing.JButton();
        services = new javax.swing.JButton();
        AboutUs = new javax.swing.JButton();
        Shop = new javax.swing.JButton();
        Contacts = new javax.swing.JButton();
        BookAppointment4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 1800));

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 1800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home.setBackground(new java.awt.Color(0, 0, 0));
        Home.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setText("HOME");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, -1));

        services.setBackground(new java.awt.Color(0, 0, 0));
        services.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        services.setForeground(new java.awt.Color(255, 255, 255));
        services.setText("SERVICES");
        services.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicesActionPerformed(evt);
            }
        });
        jPanel1.add(services, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 90, -1));

        AboutUs.setBackground(new java.awt.Color(51, 0, 0));
        AboutUs.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        AboutUs.setForeground(new java.awt.Color(255, 255, 255));
        AboutUs.setText("ABOUT US");
        AboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsActionPerformed(evt);
            }
        });
        jPanel1.add(AboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 110, -1));

        Shop.setBackground(new java.awt.Color(0, 0, 0));
        Shop.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Shop.setForeground(new java.awt.Color(255, 255, 255));
        Shop.setText("OUR PRODUCTS");
        Shop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShopActionPerformed(evt);
            }
        });
        jPanel1.add(Shop, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 150, -1));

        Contacts.setBackground(new java.awt.Color(0, 0, 0));
        Contacts.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Contacts.setForeground(new java.awt.Color(255, 255, 255));
        Contacts.setText("CONTACTS");
        Contacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactsActionPerformed(evt);
            }
        });
        jPanel1.add(Contacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 120, -1));

        BookAppointment4.setBackground(new java.awt.Color(0, 0, 0));
        BookAppointment4.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        BookAppointment4.setForeground(new java.awt.Color(255, 255, 255));
        BookAppointment4.setText("BOOK APPOINTMENT");
        BookAppointment4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookAppointment4ActionPerformed(evt);
            }
        });
        jPanel1.add(BookAppointment4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\Homepage Design\\src\\pictures\\whiteLogo.png")); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 34)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VAN SALON AND SPA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("S A L O N   &   S P A");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 170, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("our products");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 260, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("to elevate your beauty routine at home.");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 310, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\BeautySalonAndSpa\\src\\Pictures\\logooooo.png")); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 520, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Explore our premium selection of hair, skincare, and body care products ");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\BeautySalonAndSpa\\src\\Pictures\\p1.jpg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 200, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\BeautySalonAndSpa\\src\\Pictures\\p2.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 200, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\BeautySalonAndSpa\\src\\Pictures\\p3.jpg")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, -1, 190));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\BeautySalonAndSpa\\src\\Pictures\\p5.jpg")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 710, -1, 240));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\BeautySalonAndSpa\\src\\Pictures\\p6.jpg")); // NOI18N
        jLabel7.setText("jLabel6");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 710, -1, 240));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\BeautySalonAndSpa\\src\\Pictures\\p4.jpg")); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 710, -1, 240));

        background1.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        background1.setForeground(new java.awt.Color(51, 0, 0));
        background1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\Homepage Design\\src\\pictures\\background.jpg")); // NOI18N
        background1.setText("jLabel1");
        jPanel1.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 1420));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\BeautySalonAndSpa\\src\\Pictures\\993648930faa6d673ed137a215c86107.jpg")); // NOI18N
        jLabel19.setText("jLabel18");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1420, 780, 190));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1794, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        Homepage homepage = new Homepage();  // Assuming the homepage is another JFrame
        homepage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    private void AboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsActionPerformed
        // TODO add your handling code here:
        AboutUs aboutUs = new AboutUs();
        aboutUs.setVisible(true);
        this.setVisible(false);  
    }//GEN-LAST:event_AboutUsActionPerformed

    private void ContactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactsActionPerformed
        // TODO add your handling code here:
        Contacts contacts = new Contacts();
        contacts.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ContactsActionPerformed

    private void BookAppointment4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookAppointment4ActionPerformed
        // TODO add your handling code here:
         Booking booking4 = new Booking();
        booking4.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BookAppointment4ActionPerformed

    private void servicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicesActionPerformed
        // TODO add your handling code here:
        Services services = new Services();
        services.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_servicesActionPerformed

    private void ShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShopActionPerformed
        // TODO add your handling code here:
        OurProducts shop = new OurProducts();
        shop.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ShopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OurProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OurProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OurProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OurProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OurProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutUs;
    private javax.swing.JButton BookAppointment4;
    private javax.swing.JButton Contacts;
    private javax.swing.JButton Home;
    private javax.swing.JButton Shop;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton services;
    // End of variables declaration//GEN-END:variables
}
