/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package homepage.design;

/**
 *
 * @author Noreen Grace G
 */
public class Services extends javax.swing.JFrame {

    /**
     * Creates new form Services
     */
    public Services() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Home = new javax.swing.JButton();
        services = new javax.swing.JButton();
        AboutUs = new javax.swing.JButton();
        Shop = new javax.swing.JButton();
        Contacts = new javax.swing.JButton();
        BookAppointment = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        SalonServices = new javax.swing.JButton();
        SpaServices = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(700, 1620));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\Homepage Design\\src\\pictures\\whiteLogo.png")); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 140, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 34)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VAN SALON AND SPA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("S A L O N   &   S P A");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 170, -1));

        Home.setBackground(new java.awt.Color(0, 0, 0));
        Home.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setText("HOME");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 80, -1));

        services.setBackground(new java.awt.Color(51, 0, 0));
        services.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        services.setForeground(new java.awt.Color(255, 255, 255));
        services.setText("SERVICES");
        services.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicesActionPerformed(evt);
            }
        });
        jPanel1.add(services, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 90, -1));

        AboutUs.setBackground(new java.awt.Color(0, 0, 0));
        AboutUs.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        AboutUs.setForeground(new java.awt.Color(255, 255, 255));
        AboutUs.setText("ABOUT US");
        AboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsActionPerformed(evt);
            }
        });
        jPanel1.add(AboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 110, -1));

        Shop.setBackground(new java.awt.Color(0, 0, 0));
        Shop.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Shop.setForeground(new java.awt.Color(255, 255, 255));
        Shop.setText("OUR PRODUCTS");
        Shop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShopActionPerformed(evt);
            }
        });
        jPanel1.add(Shop, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 150, -1));

        Contacts.setBackground(new java.awt.Color(0, 0, 0));
        Contacts.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Contacts.setForeground(new java.awt.Color(255, 255, 255));
        Contacts.setText("CONTACTS");
        Contacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactsActionPerformed(evt);
            }
        });
        jPanel1.add(Contacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 120, -1));

        BookAppointment.setBackground(new java.awt.Color(0, 0, 0));
        BookAppointment.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        BookAppointment.setForeground(new java.awt.Color(255, 255, 255));
        BookAppointment.setText("BOOK APPOINTMENT");
        BookAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookAppointmentActionPerformed(evt);
            }
        });
        jPanel1.add(BookAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, -1, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 55)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("SERVICES");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 240, -1));

        SalonServices.setBackground(new java.awt.Color(0, 0, 0));
        SalonServices.setFont(new java.awt.Font("Segoe UI", 0, 34)); // NOI18N
        SalonServices.setForeground(new java.awt.Color(255, 255, 255));
        SalonServices.setText("SALON SERVICES");
        SalonServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalonServicesActionPerformed(evt);
            }
        });
        jPanel1.add(SalonServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, 300, 50));

        SpaServices.setBackground(new java.awt.Color(0, 0, 0));
        SpaServices.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        SpaServices.setForeground(new java.awt.Color(255, 255, 255));
        SpaServices.setText("SPA SERVICES");
        SpaServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpaServicesActionPerformed(evt);
            }
        });
        jPanel1.add(SpaServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 880, 300, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 23)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MASSAGE TREATMENT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 920, -1, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 23)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("HAIR COLOR");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, 140, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 23)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NAIL CARE");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 630, -1, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 23)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("MAKE-UP");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 580, 100, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 23)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("HAIR CUT");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, -1, 50));

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 23)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SKINCARE TREATMENT");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 850, -1, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\Homepage Design\\src\\pictures\\red.jpg")); // NOI18N
        jLabel2.setText("jLabel1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 770, 230));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\Homepage Design\\src\\pictures\\red.jpg")); // NOI18N
        jLabel9.setText("jLabel1");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 800, 770, 220));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\Homepage Design\\src\\pictures\\whiteLogo.png")); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1430, 150, 80));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\BeautySalonAndSpa\\src\\Pictures\\Pi7_instagram.png")); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 1500, -1, 20));

        jLabel24.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\BeautySalonAndSpa\\src\\Pictures\\Pi7_facebook.png")); // NOI18N
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 1500, 30, 20));

        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\BeautySalonAndSpa\\src\\Pictures\\Pi7_tiktok.png")); // NOI18N
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 1500, 30, 20));

        jLabel26.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\BeautySalonAndSpa\\src\\Pictures\\Pi7_twitter.png")); // NOI18N
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 1500, 30, 20));

        jLabel28.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("CONTACT");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 1440, -1, 20));

        jLabel29.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("BGRY BUCANA NASUGBU BATANGAS ");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 1470, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("222.888.7770");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 1490, -1, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("INFO@VANSALONANDSPA.COM");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 1510, -1, 20));

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\Homepage Design\\src\\pictures\\placeholder.png")); // NOI18N
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 1470, 30, 20));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\BeautySalonAndSpa\\src\\Pictures\\Pi7_phone.png")); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 1490, 30, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\BeautySalonAndSpa\\src\\Pictures\\Pi7_envelope-of-white-paper.png")); // NOI18N
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 1510, 30, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("© 2024 VAN Salon and Spa | All Rights Reserved | Privacy Policy ");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 1580, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("SCHEDULE");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 1430, 70, 30));

        jLabel34.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Mon: 7:00 am - 6:00 pm");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 1470, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Tue: 7:00 am - 6:00 pm");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 1490, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Wed: 7:00 am - 6:00 pm");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 1510, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Thu: 7:00 am - 6:00 pm");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 1530, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Fri: 7:00 am - 6:00 pm");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 1550, 120, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\BeautySalonAndSpa\\src\\Pictures\\Pi7_facebook.png")); // NOI18N
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 1500, 30, 20));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\BeautySalonAndSpa\\src\\Pictures\\993648930faa6d673ed137a215c86107.jpg")); // NOI18N
        jLabel18.setText("jLabel18");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1410, 770, 190));

        background.setForeground(new java.awt.Color(51, 0, 0));
        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\Homepage Design\\src\\pictures\\background.jpg")); // NOI18N
        background.setText("jLabel1");
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 1430));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1614, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        Homepage homepage = new Homepage();  // Assuming the homepage is another JFrame
        homepage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    private void AboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsActionPerformed
        // TODO add your handling code here:
         AboutUs aboutUs = new AboutUs();
         aboutUs.setVisible(true);
         this.setVisible(false); 
    }//GEN-LAST:event_AboutUsActionPerformed

    private void ContactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactsActionPerformed
        // TODO add your handling code here:
        Contacts contacts = new Contacts();
        contacts.setVisible(true);
    this.setVisible(false); 
    }//GEN-LAST:event_ContactsActionPerformed

    private void BookAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookAppointmentActionPerformed
        // TODO add your handling code here:
        Booking booking = new Booking();
        booking.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BookAppointmentActionPerformed

    private void SalonServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalonServicesActionPerformed
        // TODO add your handling code here:
        SalonServices salonServices = new SalonServices();
    salonServices.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_SalonServicesActionPerformed

    private void SpaServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpaServicesActionPerformed
        // TODO add your handling code here:
        SpaServices spaServices = new SpaServices();
    spaServices.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_SpaServicesActionPerformed

    private void ShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShopActionPerformed
        // TODO add your handling code here:
         OurProducts shop1 = new OurProducts();
        shop1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ShopActionPerformed

    private void servicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicesActionPerformed
        // TODO add your handling code here:
        Services services = new Services();
    services.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_servicesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Services().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutUs;
    private javax.swing.JButton BookAppointment;
    private javax.swing.JButton Contacts;
    private javax.swing.JButton Home;
    private javax.swing.JButton SalonServices;
    private javax.swing.JButton Shop;
    private javax.swing.JButton SpaServices;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton services;
    // End of variables declaration//GEN-END:variables
}
