/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package homepage.design;

/**
 *
 * @author Noreen Grace G
 */
public class SkincareTreatment extends javax.swing.JFrame {

    /**
     * Creates new form SkincareTreatment
     */
    public SkincareTreatment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Home = new javax.swing.JButton();
        services = new javax.swing.JButton();
        AboutUs = new javax.swing.JButton();
        Shop = new javax.swing.JButton();
        Contacts = new javax.swing.JButton();
        BookAppointment1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        BookAppointment2 = new javax.swing.JButton();
        BookAppointment3 = new javax.swing.JButton();
        BookAppointment4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(792, 1500));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home.setBackground(new java.awt.Color(0, 0, 0));
        Home.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setText("HOME");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, -1));

        services.setBackground(new java.awt.Color(51, 0, 0));
        services.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        services.setForeground(new java.awt.Color(255, 255, 255));
        services.setText("SERVICES");
        services.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicesActionPerformed(evt);
            }
        });
        jPanel1.add(services, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 90, -1));

        AboutUs.setBackground(new java.awt.Color(0, 0, 0));
        AboutUs.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        AboutUs.setForeground(new java.awt.Color(255, 255, 255));
        AboutUs.setText("ABOUT US");
        AboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsActionPerformed(evt);
            }
        });
        jPanel1.add(AboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 110, -1));

        Shop.setBackground(new java.awt.Color(0, 0, 0));
        Shop.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Shop.setForeground(new java.awt.Color(255, 255, 255));
        Shop.setText("OUR PRODUCTS");
        Shop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShopActionPerformed(evt);
            }
        });
        jPanel1.add(Shop, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 150, -1));

        Contacts.setBackground(new java.awt.Color(0, 0, 0));
        Contacts.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Contacts.setForeground(new java.awt.Color(255, 255, 255));
        Contacts.setText("CONTACTS");
        Contacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactsActionPerformed(evt);
            }
        });
        jPanel1.add(Contacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 120, -1));

        BookAppointment1.setBackground(new java.awt.Color(0, 0, 0));
        BookAppointment1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        BookAppointment1.setForeground(new java.awt.Color(255, 255, 255));
        BookAppointment1.setText("BOOK APPOINTMENT");
        BookAppointment1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookAppointment1ActionPerformed(evt);
            }
        });
        jPanel1.add(BookAppointment1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, -1, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\Homepage Design\\src\\pictures\\whiteLogo.png")); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 34)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VAN SALON AND SPA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("S A L O N   &   S P A");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 170, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("skincare treatments");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 430, -1));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("facial");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 90, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("waxing and hair removal");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 930, 430, -1));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("peels");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 640, 100, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Eyebrow Shaping");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1000, 170, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Full Body Waxing");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1030, 170, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Brazillian Waxing");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1060, 170, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Microdermabrasion");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 760, 170, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Fruit-Acid Peel");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 730, 170, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Anti-Aging Facial");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 170, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Hydrating Facial");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 170, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Classical Facial");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 170, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Chemical Peel");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 700, 170, 30));

        jLabel38.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("₱ 500.00");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 1000, 80, 30));

        jLabel39.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("₱ 1,500.00");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 1030, -1, 30));

        jLabel40.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("₱ 1,800.00");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 1060, -1, 30));

        jLabel41.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("₱ 1,500.00");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 700, -1, 30));

        jLabel45.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("₱ 1,200.00");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 730, -1, 30));

        jLabel46.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("₱ 1,000.00");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, -1, 30));

        jLabel47.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("₱ 1,100.00");
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, -1, 30));

        jLabel48.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("₱ 800.00");
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, -1, 30));

        jLabel49.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("₱ 1,800.00");
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 760, -1, 30));

        BookAppointment2.setBackground(new java.awt.Color(0, 0, 0));
        BookAppointment2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        BookAppointment2.setForeground(new java.awt.Color(255, 255, 255));
        BookAppointment2.setText("BOOK APPOINTMENT");
        BookAppointment2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookAppointment2ActionPerformed(evt);
            }
        });
        jPanel1.add(BookAppointment2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 1100, -1, 40));

        BookAppointment3.setBackground(new java.awt.Color(0, 0, 0));
        BookAppointment3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        BookAppointment3.setForeground(new java.awt.Color(255, 255, 255));
        BookAppointment3.setText("BOOK APPOINTMENT");
        BookAppointment3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookAppointment3ActionPerformed(evt);
            }
        });
        jPanel1.add(BookAppointment3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 800, -1, 40));

        BookAppointment4.setBackground(new java.awt.Color(0, 0, 0));
        BookAppointment4.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        BookAppointment4.setForeground(new java.awt.Color(255, 255, 255));
        BookAppointment4.setText("BOOK APPOINTMENT");
        BookAppointment4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookAppointment4ActionPerformed(evt);
            }
        });
        jPanel1.add(BookAppointment4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\Homepage Design\\src\\pictures\\red.jpg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 930, 780, 220));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\Homepage Design\\src\\pictures\\red.jpg")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 780, 220));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\Homepage Design\\src\\pictures\\red.jpg")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 780, 240));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\Homepage Design\\src\\pictures\\whiteLogo.png")); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1270, 150, 80));

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\BeautySalonAndSpa\\src\\Pictures\\Pi7_instagram.png")); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 1340, 30, 20));

        jLabel24.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\BeautySalonAndSpa\\src\\Pictures\\Pi7_facebook.png")); // NOI18N
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 1340, 30, 20));

        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\BeautySalonAndSpa\\src\\Pictures\\Pi7_tiktok.png")); // NOI18N
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 1340, 30, 20));

        jLabel26.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\BeautySalonAndSpa\\src\\Pictures\\Pi7_twitter.png")); // NOI18N
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 1340, 30, 20));

        jLabel28.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("CONTACT");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1270, -1, 20));

        jLabel29.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("BGRY BUCANA NASUGBU BATANGAS ");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 1300, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("222.888.7770");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 1320, -1, 20));

        jLabel21.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("INFO@VANSALONANDSPA.COM");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 1340, -1, 20));

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\Homepage Design\\src\\pictures\\placeholder.png")); // NOI18N
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1300, 30, 20));

        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\BeautySalonAndSpa\\src\\Pictures\\Pi7_phone.png")); // NOI18N
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1320, 30, 20));

        jLabel30.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\BeautySalonAndSpa\\src\\Pictures\\Pi7_envelope-of-white-paper.png")); // NOI18N
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1340, 30, 20));

        jLabel31.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("© 2024 VAN Salon and Spa | All Rights Reserved | Privacy Policy ");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1430, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("SCHEDULE");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 1260, 70, 30));

        jLabel34.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Mon: 7:00 am - 6:00 pm");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 1290, -1, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Tue: 7:00 am - 6:00 pm");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 1310, 130, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Wed: 7:00 am - 6:00 pm");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 1330, -1, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Thu: 7:00 am - 6:00 pm");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 1350, -1, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Fri: 7:00 am - 6:00 pm");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 1370, 120, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\BeautySalonAndSpa\\src\\Pictures\\993648930faa6d673ed137a215c86107.jpg")); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1250, 770, 210));

        background1.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        background1.setForeground(new java.awt.Color(51, 0, 0));
        background1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noreen Grace G\\OneDrive\\Pictures\\Documents\\NetBeansProjects\\Homepage Design\\src\\pictures\\background.jpg")); // NOI18N
        jPanel1.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 1420));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        Homepage homepage = new Homepage();  // Assuming the homepage is another JFrame
        homepage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    private void AboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsActionPerformed
        // TODO add your handling code here:
        AboutUs aboutUs = new AboutUs();
        aboutUs.setVisible(true);
        this.setVisible(false);  
    }//GEN-LAST:event_AboutUsActionPerformed

    private void ContactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactsActionPerformed
        // TODO add your handling code here:
        Contacts contacts = new Contacts();
        contacts.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_ContactsActionPerformed

    private void BookAppointment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookAppointment1ActionPerformed
        // TODO add your handling code here:
         Booking booking1 = new Booking();
        booking1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BookAppointment1ActionPerformed

    private void BookAppointment2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookAppointment2ActionPerformed
        // TODO add your handling code here:
         Booking booking2 = new Booking();
        booking2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BookAppointment2ActionPerformed

    private void BookAppointment3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookAppointment3ActionPerformed
        // TODO add your handling code here:
         Booking booking3 = new Booking();
        booking3.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BookAppointment3ActionPerformed

    private void BookAppointment4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookAppointment4ActionPerformed
        // TODO add your handling code here:
         Booking booking4 = new Booking();
        booking4.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BookAppointment4ActionPerformed

    private void servicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicesActionPerformed
        // TODO add your handling code here:
        Services services = new Services();
        services.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_servicesActionPerformed

    private void ShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShopActionPerformed
        // TODO add your handling code here: 
        OurProducts shop = new OurProducts();
        shop.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ShopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SkincareTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SkincareTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SkincareTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SkincareTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SkincareTreatment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutUs;
    private javax.swing.JButton BookAppointment1;
    private javax.swing.JButton BookAppointment2;
    private javax.swing.JButton BookAppointment3;
    private javax.swing.JButton BookAppointment4;
    private javax.swing.JButton Contacts;
    private javax.swing.JButton Home;
    private javax.swing.JButton Shop;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton services;
    // End of variables declaration//GEN-END:variables
}
