/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontdesksystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;


/**
 *
 * @author User PC
 */
public class Bill extends javax.swing.JFrame {

    /**
     * Creates new form Bill
     */
    public Bill() {
        initComponents();
        connectToDatabase();
    }
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    private void connectToDatabase() {
        try {
            // Load and register MySQL JDBC driver
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            // Establish connection to the database
            String url = "jdbc:mysql://localhost:3306/java_user_database"; // Replace with your database URL
            String username = "root"; // Replace with your username if necessary
            String password = ""; // Replace with your password if necessary
            con = DriverManager.getConnection(url, username, password);
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to connect to the database.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Billtextarea = new javax.swing.JTextArea();
        SeeBill = new javax.swing.JButton();
        Pay = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PHP = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Amount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        change = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Billtextarea.setColumns(20);
        Billtextarea.setRows(5);
        jScrollPane1.setViewportView(Billtextarea);

        SeeBill.setText("See My Current Bill");
        SeeBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SeeBillMouseClicked(evt);
            }
        });
        SeeBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeeBillActionPerformed(evt);
            }
        });

        Pay.setText("PAY");
        Pay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PayMouseClicked(evt);
            }
        });
        Pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayActionPerformed(evt);
            }
        });

        jLabel1.setText("Total Bill:");

        PHP.setText("PHP");

        jLabel3.setText("Amount:");

        jLabel2.setText("Change:");

        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(SeeBill))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PHP))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Pay)
                .addGap(163, 163, 163))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(SeeBill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(PHP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pay)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeeBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeeBillMouseClicked
       // Clear any previous data from the Billtextarea
    Billtextarea.setText(""); 
    
    // Variables to accumulate the total expenses
    double productTotal = 0.0;
    double serviceTotal = 0.0;
    
    // Prepare SQL queries
    String queryProductPurchase = "SELECT productname, quantity, price, total FROM productpurchase";
    String queryAvailServices = "SELECT servicename, serviceprice FROM availservices";
    
    try {
        // Execute the query to fetch product purchase data
        pst = con.prepareStatement(queryProductPurchase);
        rs = pst.executeQuery();
        
        // Append product purchase data to the Billtextarea and calculate the total
        Billtextarea.append("Products Purchased:\n");
        while (rs.next()) {
            String productName = rs.getString("productname");
            int quantity = rs.getInt("quantity");
            double price = rs.getDouble("price");
            double total = rs.getDouble("total");
            productTotal += total;  // Accumulate total for product purchases
            Billtextarea.append("Product: " + productName + ", Quantity: " + quantity + ", Price: " + price + ", Total: " + total + "\n");
        }
        
        // Execute the query to fetch available services data
        pst = con.prepareStatement(queryAvailServices);
        rs = pst.executeQuery();
        
        // Append available services data to the Billtextarea and calculate the total
        Billtextarea.append("\nAvailable Services:\n");
        while (rs.next()) {
            String serviceName = rs.getString("servicename");
            double servicePrice = rs.getDouble("serviceprice");
            serviceTotal += servicePrice;  // Accumulate total for services
            Billtextarea.append("Service: " + serviceName + ", Price: " + servicePrice + "\n");
        }
        
        // Calculate the overall total
        double totalExpenses = productTotal + serviceTotal;
        
        // Display the total expenses in the PHP JLabel
        PHP.setText("Total Expenses: " + totalExpenses);
        
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error retrieving bill data.", "Error", JOptionPane.ERROR_MESSAGE);
    } finally {
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_SeeBillMouseClicked

    private void PayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PayMouseClicked
        try {
        // Step 1: Get the total bill from the PHP label
        String totalBillText = PHP.getText();  // Total bill displayed in PHP JLabel
        // Extract the numeric value from the label (assuming label text format is "Total Expenses: 123.45")
        double totalBill = Double.parseDouble(totalBillText.replace("Total Expenses: ", "").trim());

        // Step 2: Get the amount input from the Amount text field
        String amountText = Amount.getText().trim();  // Get the text from Amount text field
        double amountEntered = 0.0;
        
        if (amountText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter an amount.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            amountEntered = Double.parseDouble(amountText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid amount entered. Please enter a valid number.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Step 3: Check if the entered amount is sufficient
        if (amountEntered < totalBill) {
            JOptionPane.showMessageDialog(this, "Entered amount is less than the total bill. Please enter a valid amount.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Step 4: Calculate the change (remaining balance)
        double changeBill = amountEntered - totalBill;
        
        change.setText(String.format("%.2f", changeBill));

        // Step 5: Display the remaining balance/change in the Billtextarea
        Billtextarea.append("\nPayment Details:\n");
        Billtextarea.append("Total Bill: " + totalBill + "\n");
        Billtextarea.append("Amount Entered: " + amountEntered + "\n");
        Billtextarea.append("Change/Remaining Balance: " + changeBill + "\n");
        
        

        // Step 6: Delete the data from the productpurchase and availservices tables
        // Assuming you want to delete all records from these tables after payment

        String deleteProductPurchase = "DELETE FROM productpurchase";
        String deleteAvailServices = "DELETE FROM availservices";
        
        // Database operations should be inside a try-catch block
        try (PreparedStatement pst1 = con.prepareStatement(deleteProductPurchase);
             PreparedStatement pst2 = con.prepareStatement(deleteAvailServices)) {
            
            // Execute DELETE for productpurchase table
            pst1.executeUpdate();
            
            // Execute DELETE for availservices table
            pst2.executeUpdate();
            
            // Inform the user that the data was deleted successfully
            JOptionPane.showMessageDialog(this, "Payment processed successfully. Data has been deleted from the database.", "Payment Successful", JOptionPane.INFORMATION_MESSAGE);
            
            // Step 7: Thank you message after successful deletion
            Billtextarea.append("\n\nTHANK YOU FOR VISITING OUR SPA AND SALON.\n");

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error deleting data from database.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error processing the payment.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_PayMouseClicked

    private void PayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PayActionPerformed

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_changeActionPerformed

    private void SeeBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeeBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeeBillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Amount;
    private javax.swing.JTextArea Billtextarea;
    private javax.swing.JLabel PHP;
    private javax.swing.JButton Pay;
    private javax.swing.JButton SeeBill;
    private javax.swing.JTextField change;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
